### ISSUE TITLE
Not posting checkins on Known 0.9.9-a

### ISSUE THREAD

**Issue by davidmead** [aaronpk/Teacup#13]
I haven't been able to get Teacup to post anything to my Known site at all.

Looking at the 'IndiePub' tab in Known shows it connected. I can log in and see that it creates a post on the Teacup site, https://teacup.p3k.io/davidjohnmead.com, but nothing comes through to the blog.

I revoked instances in Known. Logged out and back in and saw the new token appear in Known.

Still nothing.

**Comment by metbril** [comment]
I noticed (by debugging / logging each request) that the Teacup client does not post a 'content' item. It does publish 'summary'. For example:

```yaml
POST:
    access_token: XXXXX
    h: entry
    published: '2019-01-29T21:28:29+01:00'
    created: '2019-01-29T21:28:29+01:00'
    summary: 'Just drank: Water'
    drank: { type: h-food, properties: { name: Water } }
 ```

Perhaps that's related to your issue?
